### ISSUE TITLE
No module named 'cython_bbox'

### ISSUE THREAD

**Issue by theFreedomIWanted** [JudasDie/SOTS#13]
Many thanks for your wonderful work and the code released. But I did not know clearly how the installation is to run CSTrack since only the installation of python or pytorch like are statemented, there seems no description about 'python setup.py install' or 'python install .' like operation for CSTrack. The problem I met, namly 'No module named 'cython_bbox' ', seems due to I did not run 'python setup.py' like, but I did not know which one is needed for CSTrack.

**Comment by H11zang** [comment]
All packages needed for CSTrack are in "requirements.txt". You can run "pip install -r requirements.txt" under the path "SOTS/lib/tutorial/CSTrack/". More details are described in "cstrack.md (CSTrack tutorial)". I hope it helps.

**Comment by theFreedomIWanted** [comment]
Many thanks for you reply, and the problem has been solved when I run "pip install cython-bbox". Thanks again for your wonderful work and the code released.
