### ISSUE TITLE
[CSTrack] when computing ID-Loss, does it use only 1/8 feature?

### ISSUE THREAD

**Issue by Junhojuno** [JudasDie/SOTS#15]
```python
#ID_loss
        if i == 0:
            ps_id = id_embeding[indices_id[i]]
```
In class 'MOTLoss', the code above uses only first value of `indices_id`.

This means,I think, that 
       - indices_id[0] has the locations in which an small object exists. (it operates like mask tensor)
       - and, the 1/8-scale features are only used to compute the ID Loss. (only small objects are used for ID-Loss)

Did I understand the code in right way?

**Comment by H11zang** [comment]
It's not entirely right. The SAAN module in CSTrack aggregate all scale information in 1/8 resolution, so we only train ID loss in it. It focuses on all objects rather than the small ones.

**Comment by Junhojuno** [comment]
Aha! I misunderstood something. thanks for answering!
