### ISSUE TITLE
One More Check: Making “Fake Background” Be Tracked Again

### ISSUE THREAD

**Issue by NaifahNurya** [JudasDie/SOTS#16]
Thank you for your nice recent paper,  **"One More Check: Making “Fake Background” Be Tracked Again"** which shows high improvement in performance compared to the current state of the art in Multi-object tracking.  The link on the paper direct to this repository is where we can find the implementation, however, I didn't find its implementation. 

Also on the paper  " https://arxiv.org/pdf/2104.09441v1.pdf "stated that other information can be found in Supplementary material,  but also I didn't find those supplementary materials.

Can you share those supplementary materials? Also, when do you expect to release the code of this paper??

Thank you again for your nice work.

**Comment by JudasDie** [comment]
> Thank you for your nice recent paper, **"One More Check: Making “Fake Background” Be Tracked Again"** which shows high improvement in performance compared to the current state of the art in Multi-object tracking. The link on the paper direct to this repository is where we can find the implementation, however, I didn't find its implementation.
> 
> Also on the paper " https://arxiv.org/pdf/2104.09441v1.pdf[![](chrome-extension://gmpljdlgcdkljlppaekciacdmdlhfeon/images/beside-link-icon.svg)](https://docs.google.com/viewer?url=https%3A%2F%2Farxiv.org%2Fpdf%2F2104.09441v1.pdf&embedded=true&chrome=false&dov=1) "stated that other information can be found in Supplementary material, but also I didn't find those supplementary materials.
> 
> Can you share those supplementary materials? Also, when do you expect to release the code of this paper??
> 
> Thank you again for your nice work.

Hi, thanks for your interest. It will be released in June or July. We would upload the supp. later.

**Comment by NaifahNurya** [comment]
@JudasDie  Thank you for your reply.  

I am waiting for it.

**Comment by NaifahNurya** [comment]
@JudasDie , Any updates on this??

**Comment by Leo63963** [comment]
@JudasDie Waiting for the code for **"One More Check: Making “Fake Background” Be Tracked Again" ** as well. Hopefully to be released soon.

**Comment by JudasDie** [comment]
> @JudasDie Waiting for the code for "One More Check: Making “Fake Background” Be Tracked Again" as well. Hopefully to be released soon. Thanks.

The code for CSTrackV2 will be released in early Dec. (after AAAI final results).
