### ISSUE TITLE
[CSTrack] Trained on 640 with batch_size=8 or 10?

### ISSUE THREAD

**Issue by Junhojuno** [JudasDie/SOTS#17]
Now, I keep trying to train a CSTrack model. 
I set the `batch_size=2,4,6,8` and `input_size=640` but, I can't train it because of CUDA out of memory error.
only a setting(`batch_size=1` and `input_size=640`) operated well...
(mainly, CUDA out of error, my computer is set to 2060 super * 2, and used to train on only 1 GPU)

I don't know exactly what is wrong..

I think the CSTrack model is trained on 2080TI with `batch_size=8 or 10` and `input_size=640`.

is it right..?!

**Comment by H11zang** [comment]
I trained CSTrack on 2080 Ti with batch_size = 8 or 10 and input_size = (1088,608). If you train CSTrack on 1 GPU (2060 memory is 6G）, you can only set the batch_size = 2,4 with the input_size = (1088,608), alternatively reduce the input_size to (640,480) or smaller.

**Comment by Junhojuno** [comment]
thanks a lot! 
It should be considered more.
