### ISSUE TITLE
When will SiamMOT's code be released?

### ISSUE THREAD

**Issue by valuefish** [JudasDie/SOTS#18]
When will SiamMOT's code be released?

**Comment by JudasDie** [comment]
> When will SiamMOT's code be released?

Hi, thanks for your interest. It will be released in June or July.

**Comment by YmanChris** [comment]
Today is the last day of July.

**Comment by JudasDie** [comment]
The code will be released in early Dec. (after AAAI results).

**Comment by JudasDie** [comment]
> When will SiamMOT's code be released?

Code has been released.
