### ISSUE TITLE
[CSTrack] max_index setting in `LoadImagesAndLabels ` class

### ISSUE THREAD

**Issue by Junhojuno** [JudasDie/SOTS#19]
Hello! I have a question about `max_index` setting in `LoadImagesAndLabels`
```python
for ds, label_paths in self.label_files_dict.items():
          max_index = -1
          for lp in label_paths:
              lb = np.loadtxt(lp)
              if len(lb) < 1:
                  continue
              if len(lb.shape) < 2:
                  img_max = lb[1]
              else:
                  img_max = np.max(lb[:, 1])
              if img_max > max_index:
                  max_index = img_max
          self.tid_num[ds] = max_index + 1 # here

      last_index = 0
      for i, (k, v) in enumerate(self.tid_num.items()):
                self.tid_start_index[k] = last_index
                last_index += v
```
when `self.tid_num[ds]=max_index+1` is applied to all dataset, index i think that is not used occur.

ex) 
|dataset|id range|max_index + 1|tid_start_index|
|:------:|:---:|:---:|:---:|
|mot17|1~517|518|0|
|mot20|1~2215|2216|518|
|mot16|1~517|518|2734|

Between `mot20` and `mot16`, an index 2733 is not used.

Does you have any other reason why `self.tid_num[ds]=max_index+1` is applied to all dataset, not applying only first dataset?

**Comment by H11zang** [comment]
Sorry, I am not clear with your problem. The num of ID would only be used to Initialize the FC layer, which maps the embedding from 512 to N (N denotes the number of ID, e.g., 518 for MOT17).  The output will be compared with the one-hot representation of the GT class label (ID) to learn ID embeddings.

**Comment by Junhojuno** [comment]
I also understand the training procedure of embedding representation,
 but I am still confused with integrating id values of datasets.
- `mot17` is the first dataset on the table above, so its `tid_start_index` is 0.
- `mot20` is the second dataset and its id range is converted from `1~2215` to `518~2732` as `mot20` has `tid_start_index=518`
- `mot16` is the last dataset and its id range is also converted. 
- However, its(`mot16`) `tid_start_index` is set to 2734 according to the code `LoadImagesAndLabels`, not 2733.
Furthermore, `self.nID` is set to `int(last_index) + 1`. 

I have been thinking that the `tid_start_index` of `mot16` might be 2733 because the last index of 'mot20` is converted and set to 2732.

(I think) It could make unused feature dimension when computing Crossentropy Loss.

I have known this code is correctly operated, but still not been clear.

(now, I am customizing the CSTrack codes. I'm wondering if I could change the lines above.)

**Comment by H11zang** [comment]
Thank you for your question. I think you can have a try but it may be work a little. The probable reason is that the ID embedding is mapped as a one-hot representation during training. However, during testing, we directly use ID embedding to associate by the cosine distance metric. The misalignment between training and testing would make it insensitive to the number of IDs. (I think, but I am not sure. If you have any new findings on this issue, please share with me. )

**Comment by Junhojuno** [comment]
Thanks for answering my question. 
I think I need to understand the whole input pipeline more:)
If I find new issues or etc, I will share it. Thanks.
