### ISSUE TITLE
About CSTrack

### ISSUE THREAD

**Issue by JunnHan** [JudasDie/SOTS#2]
Thanks for your great work! I noticed that CSTrack use the attention mechanism as one of the important module, but you do not provide the attention map visualization results in your paper. And I'm wondering how to visualize the attention map.

**Comment by JudasDie** [comment]
> Thanks for your great work! I noticed that CSTrack use the attention mechanism as one of the important module, but you do not provide the attention map visualization results in your paper. And I'm wondering how to visualize the attention map.

@H11zang , could you kindly help @JunnHan with this question? It would be great to provide a visualization code (if possible).

**Comment by H11zang** [comment]
Thanks for your interest in our work. You could modify the code of CCN in SOTS/lib/models/mot/cstrack.py to visualize the attention map you need. I will release a visualization code later.
