### ISSUE TITLE
在test_cstrack_panda_post_process.py参数的含义?

### ISSUE THREAD

**Issue by lpxgis** [JudasDie/SOTS#21]
老师您好,我最近在学习您这个项目中的一些代码,我不是很清楚test_cstrack_panda_post_process.py文件中参数的含义,如果有可能的话,能麻烦您简单解释一下吗?是为了优化MOTA分数吗

**Comment by H11zang** [comment]
你好，test_cstrack_panda_post_process.py文件中主要的作用是利用全局信息对序列做一些简单的后处理，包括插值，删除短轨，和轨迹缝合。
参数含义如下：
轨迹缝合
matching_len   两个轨迹的最大帧间隔
body_dis          两个轨迹的最大允许距离（身位，目标有大小）
box_ratio         两个轨迹的框大小差异限制
crowd_num     人群密集限制，低于某个密集度从缝合轨迹

删除短轨
def_leg_thres   轨迹长度低于某个阈值直接删除

插值
add_leg_thres  轨迹长度，长于某个阈值可以插值
frame_thres     前后两帧的间隔阈值
interplation_ratio_thres    间隔占长度比的阈值

希望有所帮助。

**Comment by lpxgis** [comment]
谢谢您了，真的是帮我解决了很大的疑惑，十分感谢🐱‍🏍
祝您一切顺利！
