### ISSUE TITLE
如何使用自己的det.txt呢？

### ISSUE THREAD

**Issue by lpxgis** [JudasDie/SOTS#22]
你好，我想请教下如何在cstrack中使用自己的检测结果呢，我注意到您在test_cstrack_panda.py中给出了相应参数以便于融合自己的det结果，但是因为panda数据集本身图片分辨率很大，您加入了分割图片的机制，我想用于mot20这样的数据集做一些测试，因为其本身图片就1920*1080，不想延用分割，那么我大概需要修改哪些文件呢，或者能否在test_cstrack.py加入一些代码来融合自己的det结果呢？🐱‍🚀

**Comment by H11zang** [comment]
你可以尝试下用原版的cstrack，或者把panda版本中分割的尺度设置为空，这样会只用原图进行推理。

**Comment by lpxgis** [comment]
好的，十分感谢
