### ISSUE TITLE
replace the detection result of CSTrack only using the association.

### ISSUE THREAD

**Issue by QiyuLuo** [JudasDie/SOTS#23]
Have you provided this code? Where is this module located? Thank you for your help.

**Comment by H11zang** [comment]
Sorry, we don't provide this code. But you can modify the lib/tracker/cstrack.py to do it. And more details can be found in lib/tracker/cstrack_panda.py where we provided a simple API for external detection results.

**Comment by QiyuLuo** [comment]
Thank you for your reply.
