### ISSUE TITLE
No module named 'models.yolo'

### ISSUE THREAD

**Issue by YmanChris** [JudasDie/SOTS#25]
I run the command "python train_cstrack.py", and weights dir has yolov5l.pt file. The problem is occured. 
![image](https://user-images.githubusercontent.com/18142592/124270568-f51aec80-db6e-11eb-83b4-d0f1d8bffb92.png)

**Comment by H11zang** [comment]
I think the problem may be that you have not used the yolov5l.pt file we provided.
You can download it from the following link and try again.
Yolov5l.pt for CSTrack: https://drive.google.com/file/d/1qJHNlEXPVirDVmWL7hHeU4-P9amWHJHR/view

**Comment by YmanChris** [comment]
> I think the problem may be that you have not used the yolov5l.pt file we provided.
> You can download it from the following link and try again.
> Yolov5l.pt for CSTrack: https://drive.google.com/file/d/1qJHNlEXPVirDVmWL7hHeU4-P9amWHJHR/view

Thanks.  I do that and it works.
Best wishes.
