### ISSUE TITLE
There is a question about test_cstrack.py

### ISSUE THREAD

**Issue by zwls221** [JudasDie/SOTS#26]
Hello, I want to save the output result as a video when I run test_cstrack.py. but I find that vis.plot_tracking is missing on line 89. Would you please tell me which file it is in?

**Comment by H11zang** [comment]
If you would like to visualize the detection results and the ID embeddings matching of CSTrack, you can run test_cstrack.py with "--vis_state 1".  Moreover, if you would like to visualize the tracking results, you can modify the input/output path in SOTS/lib/utils/preview_MOT.py and run it.
