### ISSUE TITLE
cstrack训练效果很差

### ISSUE THREAD

**Issue by yuanxiaoxiaogit** [JudasDie/SOTS#28]
您好，我用crowdhuman来训练cstrack模型的时候，训练速度很慢，gpu使用率波动很大，一下百分之百，一下百分之零，我尝试调整num_work数量，但是cpu使用率始终只用了一个核，不知道要怎么解决这个问题；第二个问题是我用yolov5l做预训练模型，但训练效果很不理想，recall一直降低，不知道要怎么解决这个问题；第三个问题是您网站上提供的yolov5l模型和cstrack.pt模型是在哪个数据集上训练的结果呢

**Comment by H11zang** [comment]
你好，
第一个问题：我没遇到过哈，但是之前已经有很多人交流过说可以正常训练测试，训练代码应该是没有问题的。我猜测可能是某个部分的版本问题（如cuda、pytorch或者python中的包），抱歉提供不了帮助。
第二个问题：可以考虑可视化一下crowdhuman的gt有没有构建对，训练效果不理想有很大可能性是构建的gt和代码中的读取不是相同的格式（猜测~因为我用crowdhuman训练时候是正常的）
第三个问题：yolov5l.pt是在coco上训练的，cstrack.pt是在7个混合数据集上训练的，详细见tutorial。https://github.com/JudasDie/SOTS/blob/master/lib/tutorial/CSTrack/cstrack.md

**Comment by yuanxiaoxiaogit** [comment]
谢谢您的回答，我这个crowdhuman的处理是用下面的脚本处理的，处理的结果是下面这种格式：
处理脚本：
import os.path as osp
import os
import cv2
import json
import numpy as np


def mkdirs(d):
    if not osp.exists(d):
        os.makedirs(d)


def load_func(fpath):
    print('fpath', fpath)
    assert os.path.exists(fpath)
    with open(fpath, 'r') as fid:
        lines = fid.readlines()
    records =[json.loads(line.strip('\n')) for line in lines]
    return records


def gen_labels_crowd(data_root, label_root, ann_root):
    mkdirs(label_root)
    anns_data = load_func(ann_root)

    tid_curr = 0
    for i, ann_data in enumerate(anns_data):
        print(i)
        image_name = '{}.jpg'.format(ann_data['ID'])
        img_path = os.path.join(data_root, image_name)
        anns = ann_data['gtboxes']
        img = cv2.imread(
            img_path,
            cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION
        )
        img_height, img_width = img.shape[0:2]
        for i in range(len(anns)):
            if 'extra' in anns[i] and 'ignore' in anns[i]['extra'] and anns[i]['extra']['ignore'] == 1:
                continue
            x, y, w, h = anns[i]['fbox']
            x += w / 2
            y += h / 2
            label_fpath = img_path.replace('images', 'labels_with_ids').replace('.png', '.txt').replace('.jpg', '.txt')
            label_str = '0 {:d} {:.6f} {:.6f} {:.6f} {:.6f}\n'.format(
                tid_curr, x / img_width, y / img_height, w / img_width, h / img_height)
            with open(label_fpath, 'a') as f:
                f.write(label_str)
            tid_curr += 1

def odgt_to_txt(file_path):
    res = load_func(file_path)
    save_path = file_path.replace('odgt', 'txt')
    with open(save_path, 'a') as f:
        print(res, file=f)


if __name__ == '__main__':
    root_path = os.path.expanduser("~/zzzj/projects/")
    print(root_path)
    data_val = root_path + '/crowdhuman/images/val'
    label_val = root_path + '/crowdhuman/labels_with_ids/val'
    ann_val = root_path + '/crowdhuman/annotation_val.odgt'
    data_train = root_path + '/crowdhuman/images/train'
    label_train = root_path + '/crowdhuman/labels_with_ids/train'
    ann_train = root_path + '/crowdhuman/annotation_train.odgt'
    gen_labels_crowd(data_train, label_train, ann_train)
    gen_labels_crowd(data_val, label_val, ann_val)
    # odgt_to_txt(ann_train)

处理的最终格式：
0 24241 0.249023 0.967789 0.554688 1.109810
0 24242 0.803223 0.927526 0.481445 1.076135
0 24243 0.208496 0.638360 0.260742 1.060029
0 24244 0.481445 0.711567 0.324219 0.878477
0 24245 0.674805 0.628111 0.406250 0.729136
0 24246 0.501953 0.392387 0.275391 0.345534
0 24247 0.502930 0.327965 0.193359 0.357247
0 24248 0.408691 0.297950 0.114258 0.291362
0 24249 0.268555 0.306735 0.205078 0.273792
0 24250 0.020508 0.161786 0.056641 0.224012
0 24251 0.297363 0.130307 0.038086 0.158126
0 24252 0.383789 0.105417 0.027344 0.099561
不知道是不是这种格式呢

**Comment by H11zang** [comment]
这是我的格式
0 -1 0.179688 0.773585 0.0875 0.272537
0 -1 0.145313 0.754717 0.084375 0.278826
0 -1 0.13125 0.716981 0.05 0.163522
0 -1 0.264062 0.712788 0.0625 0.109015
0 -1 0.271875 0.687631 0.0375 0.129979
0 -1 0.307812 0.716981 0.035937 0.106918
0 -1 0.317188 0.698113 0.039062 0.134172
0 -1 0.346875 0.716981 0.040625 0.109015
0 -1 0.373437 0.712788 0.060937 0.106918
0 -1 0.38125 0.710692 0.039062 0.121593
0 -1 0.526563 0.658281 0.034375 0.098532
0 -1 0.728125 0.647799 0.028125 0.085954
0 -1 0.703125 0.641509 0.029687 0.085954
0 -1 0.682813 0.641509 0.01875 0.073375
0 -1 0.695312 0.639413 0.023438 0.073375

如果是检测数据集第二行id应该设置为-1，这样计算reid的损失会跳过，不然reid的损失没法收敛，很难和检测损失平衡。

**Comment by yuanxiaoxiaogit** [comment]
![1627288429](https://user-images.githubusercontent.com/45256165/126959202-e57b3536-91e3-46a7-a660-90e88c8d8a6e.png)
你好，我将第二行都设置为-1的时候，训练的效果如图所示，我不太懂为什么recall会一直下降

**Comment by H11zang** [comment]
验证集的召回率下降是正常的，一般最后会收敛到一个值然后波动（我的理解是precision上升带来的必然结果，判断肯定多少会错判一些目标）。我训练的时候一般recall有段时间会比较高，后面precision上来后，recall会下去然后收敛到一个合适的范围。

**Comment by yuanxiaoxiaogit** [comment]
非常感谢您的回答，您的代码支持多分类吗

**Comment by H11zang** [comment]
支持，把SOTS/experiments/model_set/xx.yaml的nc设置为你需要的类别数就可以了哈

**Comment by yuanxiaoxiaogit** [comment]
作者，您好，我用您训练的模型去测试视频，发现只要坐着的人都检测不出来，不知道您有什么改进建议吗

**Comment by H11zang** [comment]
可以检测出来，你测试把min_shape_ratio从0.6设置为10就行，这个参数会把w/h小于0.6的框都去除了，因为有部分数据集认为这类框是误检。

**Comment by H11zang** [comment]
可以检测出来，你测试把min_shape_ratio从0.6设置为10就行，这个参数会把w/h小于0.6的框都去除了。

**Comment by yuanxiaoxiaogit** [comment]
您好，您论文提到的cstrackV2什么时候公开代码呢

**Comment by H11zang** [comment]
又做了一些新的改进，可能还要一段时间（大概年末前呢），最近在秋招找工作。。进度有点慢

**Comment by yuanxiaoxiaogit** [comment]
你好，请教一下目标id总数您是在代码中如何设置的，我好像没找到

**Comment by H11zang** [comment]
训练的id总数是从数据集中统计出来的，不用设置
