### ISSUE TITLE
New version of CSTrack

### ISSUE THREAD

**Issue by PLester** [JudasDie/SOTS#3]
Great job!!! Thank you very much!!!
And when will u release the new version of CSTrack?

**Comment by H11zang** [comment]
I will release the new version of CSTrack when I finish cleaning the code.

**Comment by PLester** [comment]
@H11zang LOOK FORWARD TO IT! Thanks!

**Comment by PLester** [comment]
@H11zang 
Hello!
Could you tell me the parameters of conf_thres and nms_thres? And should the DIoU_NMS topk (200) number be set as a larger number, when you test on the MOT2020.
Thanks!
