### ISSUE TITLE
找不到MOT15/labels_with_ids文件

### ISSUE THREAD

**Issue by Leon1995-ai** [JudasDie/SOTS#30]
您好！
我在训练CSTtrack时，按照教程放置了应有的所有训练集，并在json文件中修改了路径。但运行train_cstrack.py时报错：Exception: Error loading data from ../lib/dataset/mot/data/mot15.val: G:/datasets\MOT15/labels_with_ids/train/ADL-Rundle-6/img1/000001.txt not found.
请问我该从哪里得到MOT15/labels_with_ids文件呢？另外，明明没有在MOT15上训练，为什么需要这个数据集呢？
感谢！

**Comment by H11zang** [comment]
只是用来做了其中一部分来做验证集哈，可以通过MOT challenge的提供的label文件转换一下。
这是我转好的，可以直接使用。
https://pan.baidu.com/s/1Cm_vSqqCLmLGd5Hnv25YaQ 提取码：mt15

**Comment by YangParky** [comment]
> 
可以麻烦提供一下MOT20和MO16的labels_with_ids文件吗，或者转换的文件
