### ISSUE TITLE
Compile dcn in Cuda 11.1 for RTX3080

### ISSUE THREAD

**Issue by LouisShen233** [JudasDie/SOTS#31]
When I run setup.py, it won't work. I notice this may be because deformable conv can't be compiled in Cuda 11.1 for RTX3080(can't use Cuda10 there). Have you encountered this problem?

**Comment by JudasDie** [comment]
> When I run setup.py, it won't work. I notice this may be because deformable conv can't be compiled in Cuda 11.1 for RTX3080(can't use Cuda10 there). Have you encountered this problem?

Pls use the new codebase. No more setup now,
