### ISSUE TITLE
关于匹配算子

### ISSUE THREAD

**Issue by sirius541** [JudasDie/SOTS#33]
作者您好，关于您的论文我想问您一个问题。您的 Concatenation 算子中，模板帧特征经过roi后是通过copy这组特征得到一个和search同尺寸的特征，对吗

**Comment by sirius541** [comment]
> 作者您好，关于您的论文我想问您一个问题。您的 Concatenation 算子中，模板帧特征经过GAP后是通过copy这组特征得到一个和search同尺寸的特征，对吗

**Comment by JudasDie** [comment]
> 作者您好，关于您的论文我想问您一个问题。您的 Concatenation 算子中，模板帧特征经过roi后是通过copy这组特征得到一个和search同尺寸的特征，对吗

对的，模板的输出是1*1*C，然后和搜索图像所有位置进行拼接
