### ISSUE TITLE
在MOT15训练集上的评估结果与论文中给出的差距很大

### ISSUE THREAD

**Issue by zwls221** [JudasDie/SOTS#34]
作者您好，我使用您提供的预训练权重cstrack.pt验证在MOT15训练集上的性能，参数nms_thres=0.6，conf_thres=0.5，img_size = (1088, 608)，评估code使用https://github.com/JonathonLuiten/TrackEval，但是获得的效果很差MOTA只有54%，您能告诉我可能是什么原因吗？
![SharedScreenshot](https://user-images.githubusercontent.com/58594561/130340479-feadcff1-9e62-4d69-8ecd-8692b6d7db59.jpg)

**Comment by H11zang** [comment]
公布的cstrack.pt和我之前做消融实验的参数不同的。消融实验只是在mot17的数据集上进行训练，然后在mot15上进行测试，而且去除了和mot15中重复的序列（主要是标注不同还有为了更公平）。公布的权重是在所有数据集上做训练的，对人的检测效果更好，对密集检测的场景更友好（加入了crowdhuman的数据集），但对mot15的场景可能会因为gap问题带来一定的误检，而本来mot15的序列框就很少，少量误检就可能会带来分数的很大下降。

**Comment by zwls221** [comment]
非常感谢您的回答。
