### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by Jee-King** [JudasDie/SOTS#35]
使用GOT10K测试是，experiments/test/ 路径下缺少文件 GOT10K/Ocean.yaml

在测试 load dataset 过程中，https://github.com/JudasDie/SOTS/blob/f6607a7ad4274c44a3e4c9b4799896d76505bc38/lib/utils/utils.py#L533
[gt] 是不是应该是 gt？

**Comment by JudasDie** [comment]
> 使用GOT10K测试是，experiments/test/ 路径下缺少文件 GOT10K/Ocean.yaml
> 
> 在测试 load dataset 过程中，
> 
> https://github.com/JudasDie/SOTS/blob/f6607a7ad4274c44a3e4c9b4799896d76505bc38/lib/utils/utils.py#L533
> 
> 
> [gt] 是不是应该是 gt？

你好，是为了把他放到列表里面，和其他数据集保持一致。请参考新的codebase，got10k参数在yaml里面了。
