### ISSUE TITLE
How to get the tracking results on OTB100 for different challenging attributes?

### ISSUE THREAD

**Issue by suyeH** [JudasDie/SOTS#39]
Hi, Table 1 of your paper "Learn to Match: Automatic Matching Network Design for Visual Tracking" provides the comparison of the performance of different challenging attributes on the OTB dataset. Can you provide the position of your codebase where implement this feature?
![image](https://user-images.githubusercontent.com/23137816/132734434-247d53cd-9b6a-47ea-a2f0-b7a1752a4293.png)

**Comment by JudasDie** [comment]
> Hi, Table 1 of your paper "Learn to Match: Automatic Matching Network Design for Visual Tracking" provides the comparison of the performance of different challenging attributes on the OTB dataset. Can you provide the position of your codebase where implement this feature? ![image](https://user-images.githubusercontent.com/23137816/132734434-247d53cd-9b6a-47ea-a2f0-b7a1752a4293.png)

Hi, you can use pysot-evaluation-toolkit.
