### ISSUE TITLE
CSTrack  New Version

### ISSUE THREAD

**Issue by PXThanhLam** [JudasDie/SOTS#4]
Your job is great and inspired me a lot ( I'm currently working on MOT and have gained some promised result ). I notice that your result on paper ( 70.6 MOTA) and on Mot Server (74.8 MOTA) is different. Could you inform what improve you have done ( i.e change the backbone) and update your work to new version of the paper on arxiv, thanks very much

**Comment by H11zang** [comment]
Thank you for your interest in our work. The new version  simply changes the training method of box regression, which is helpful in adapting to MOT detection scenarios.The new paper will be updated after the experiment is completed.

**Comment by PLester** [comment]
@H11zang 
Hello! 
Could you tell me the parameters of **conf_thres** and **nms_thres**? And should the DIoU_NMS topk (200) number be set as a larger number, when you test on the MOT2020. 
Thanks!

**Comment by PXThanhLam** [comment]
@H11zang  Looks forward to it !

**Comment by Bian-666** [comment]
> Thank you for your interest in our work. The new version simply changes the training method of box regression, which is helpful in adapting to MOT detection scenarios.The new paper will be updated after the experiment is completed.

您好，现在github仓库的cstrack版本是否更新为MOTA74.9的新版，我复现的结果只有70，还是旧版cstrack的指标
