### ISSUE TITLE
SOTS/experiment/train/ocean.yaml中got10k数据集的all.json找不到

### ISSUE THREAD

**Issue by n1-k0** [JudasDie/SOTS#41]
你好，我按照readme处理了got10k的数据集，依然找不到all.json这个文件，代码中也没找到涉及all.json的位置。

**Comment by JudasDie** [comment]
> 你好，我按照readme处理了got10k的数据集，依然找不到all.json这个文件，代码中也没找到涉及all.json的位置。

你好，可以用pysot提供的训练集。或者百度云盘里面的。百度云盘每个数据对应的文件夹里有json文件，如果没有all.json的话用train.json替代。百度网盘链接见SOT 的readme
