### ISSUE TITLE
ICCV 2021 Workshop GigaVision I: Multi-Object Tracking提交问题

### ISSUE THREAD

**Issue by zhonglinliu123** [JudasDie/SOTS#42]
你好，我用你提供的cstrack_panda.pt, 来跑ICCV 2021 Workshop GigaVision I: Multi-Object Tracking这个比赛的测试集，把跑出来的结果框画回到原图很多是正确的， 但是为什么提交文件没分数，有时候有分数了显示0分？          这个问题可能不是模型、代码相关的问题，因为我看见你也参加了这个比赛，所以想问问你，

**Comment by JudasDie** [comment]
> 你好，我用你提供的cstrack_panda.pt, 来跑ICCV 2021 Workshop GigaVision I: Multi-Object Tracking这个比赛的测试集，把跑出来的结果框画回到原图很多是正确的， 但是为什么提交文件没分数，有时候有分数了显示0分？ 这个问题可能不是模型、代码相关的问题，因为我看见你也参加了这个比赛，所以想问问你，

Hi, sorry for the delayed replay, For issues not related to the repo or paper, you could directly email the author.
