### ISSUE TITLE
Code for CSTrackV2

### ISSUE THREAD

**Issue by Leo63963** [JudasDie/SOTS#43]
Hi 
Really admire the work "One More Check: Making “Fake Background” Be Tracked Again". 
Just kindly ask, any plans to release the corresponding code? 
Thanks.

**Comment by JudasDie** [comment]
> Hi Really admire the work "One More Check: Making “Fake Background” Be Tracked Again". Just kindly ask, any plans to release the corresponding code? Thanks.

Thanks for your interest. The code will be released in early Dec.

**Comment by JudasDie** [comment]
> Hi Really admire the work "One More Check: Making “Fake Background” Be Tracked Again". Just kindly ask, any plans to release the corresponding code? Thanks.

Hi, the code has been released (namely OMC).

**Comment by Leo63963** [comment]
Hi, thanks for the reply.
Have you removed the code for OMC ?
