### ISSUE TITLE
Question about multi_class object tracking.

### ISSUE THREAD

**Issue by shiweizhu** [JudasDie/SOTS#45]

**Comment by shiweizhu** [comment]
I saw the introduction in the readme that the current version Only supports single-class multi-object tracking.I want to ask if it performs badly，the multi_classes tracking  version acquires a bad metrics. Have you tried it?

**Comment by H11zang** [comment]
Due to the lack of the dataset for training the multi_classes tracking, I didn't try it.

**Comment by shiweizhu** [comment]
> Due to the lack of the dataset for training the multi_classes tracking, I didn't try it.

thank you for your reply，I‘m going to do some attempts based on your excellent work

**Comment by shiweizhu** [comment]
closed
