### ISSUE TITLE
About replacing the cross-correlation to concatenation in Ocean

### ISSUE THREAD

**Issue by lhnynl** [JudasDie/SOTS#46]
Hi author, thank you for your excellent work. It is mentioned in the article that Ocean’s DW-XCorr is replaced with concatenation, but the Ocean feature combinationpart uses different dilation, resulting in irregular output sizes, and the final concatenation results cannot be directly added. So I want to know how to deal with this problem?

**Comment by JudasDie** [comment]
> Hi author, thank you for your excellent work. It is mentioned in the article that Ocean’s DW-XCorr is replaced with concatenation, but the Ocean feature combinationpart uses different dilation, resulting in irregular output sizes, and the final concatenation results cannot be directly added. So I want to know how to deal with this problem?

Hi, thanks for the interest. The multi-dilation module is removed when conducting ablation experiments. One simple choice is to set the ``LTM'' in AutoMatch to the operator you choose.

**Comment by lhnynl** [comment]
OK. I see. Thank you for your answer!
