### ISSUE TITLE
onnx export 

### ISSUE THREAD

**Issue by philip-fu** [JudasDie/SOTS#47]
Hi, I am interested in trying CSTrack/OMC for my use case. I am using triton server for inference. Does CSTrack/OMC support onnx or trt export? Just wanted to confirm with you beforehand. Thanks!

**Comment by H11zang** [comment]
Sorry, this version doesn't support onnx and trt.

**Comment by H11zang** [comment]
We will release a new version, which supports edge computing in 2022. Thanks for your interest.
