### ISSUE TITLE
[OMC] 第一阶段的训练没有问题，但是在训recheck的时候报错了

### ISSUE THREAD

**Issue by 1145284121** [JudasDie/SOTS#48]
Scaled weight_decay = 0.0004921875
Optimizer groups: 135 .bias, 148 conv.weight, 121 other
Traceback (most recent call last):
  File "train_omc.py", line 742, in <module>
    main(opt)
  File "train_omc.py", line 640, in main
    train(opt.hyp, opt, device)
  File "train_omc.py", line 266, in train
    optimizer.load_state_dict(ckpt['optimizer'])
  File "/root/miniconda3/envs/omc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 146, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

![ZTPGE8}EQMFD(~M)JEWD4)2](https://user-images.githubusercontent.com/41956449/154940920-080a3dd3-95de-41ee-b562-accf246c71e8.png)

训练使用单卡2080ti，batch 6

如果跳过optimizer的话，载入siammot也会报错
![ZTPGE8}EQMFD(~M)JEWD4)2](https://user-images.githubusercontent.com/41956449/154941190-8e2455dc-3b40-4e95-afff-c860ed3b8507.png)

**Comment by adda1221** [comment]
> Scaled weight_decay = 0.0004921875 Optimizer groups: 135 .bias, 148 conv.weight, 121 other Traceback (most recent call last): File "train_omc.py", line 742, in main(opt) File "train_omc.py", line 640, in main train(opt.hyp, opt, device) File "train_omc.py", line 266, in train optimizer.load_state_dict(ckpt['optimizer']) File "/root/miniconda3/envs/omc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 146, in load_state_dict raise ValueError("loaded state dict contains a parameter group " ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
> 
> ![ZTPGE8}EQMFD(~M)JEWD4)2](https://user-images.githubusercontent.com/41956449/154940920-080a3dd3-95de-41ee-b562-accf246c71e8.png)
> 
> 训练使用单卡2080ti，batch 6
> 
> 如果跳过optimizer的话，载入siammot也会报错 ![ZTPGE8}EQMFD(~M)JEWD4)2](https://user-images.githubusercontent.com/41956449/154941190-8e2455dc-3b40-4e95-afff-c860ed3b8507.png)

我也遇到了这个问题

**Comment by JackWoo0831** [comment]
same problem...
