### ISSUE TITLE
关于匹配算子

### ISSUE THREAD

**Issue by NeverMoreLCH** [JudasDie/SOTS#49]
你好，@JudasDie 

关于AutoMatch，我有几个问题想请教一下。

问题一：
根据你的代码，在L2Mregression和L2Mclassification的初始化中，都已经确定了使用哪两个算子。比如在L2Mregression的__init__函数中，设置了self.LTM = LTM(inchannel=256, used=[5, 6])。请问此处的[5, 6]是根据NAS（论文中提到的第一个训练阶段？）得到的嘛？

问题二：
在如问题一提到的__init__函数下，是不是意味着，你提供的训练指令“python tracking/onekey.py --cfg experiments/AutoMatch.yaml”只包含了第二个训练阶段（因为使用哪两个匹配算子已经固定了）？

问题三：
如果我想要进行第一个阶段的训练，该怎么实现呢？

非常感谢！

**Comment by JudasDie** [comment]
> 你好，@JudasDie
> 
> 关于AutoMatch，我有几个问题想请教一下。
> 
> 问题一： 根据你的代码，在L2Mregression和L2Mclassification的初始化中，都已经确定了使用哪两个算子。比如在L2Mregression的__init__函数中，设置了self.LTM = LTM(inchannel=256, used=[5, 6])。请问此处的[5, 6]是根据NAS（论文中提到的第一个训练阶段？）得到的嘛？
> 
> 问题二： 在如问题一提到的__init__函数下，是不是意味着，你提供的训练指令“python tracking/onekey.py --cfg experiments/AutoMatch.yaml”只包含了第二个训练阶段（因为使用哪两个匹配算子已经固定了）？
> 
> 问题三： 如果我想要进行第一个阶段的训练，该怎么实现呢？
> 
> 非常感谢！

是的，只包含了第二阶段训练，暂时没有放第一个阶段训练代码，因为正在优化搜索算法。如果你自己要做搜索这个task，建议用SPOS那个系列的NAS算法进行搜索。

**Comment by xyl-507** [comment]
作者您好，请问一下，您们automatch的训练代码预计什么时候能公布呀？
