### ISSUE TITLE
pytorch版本1.1？

### ISSUE THREAD

**Issue by codylcs** [JudasDie/SOTS#5]
[老项目](https://github.com/researchmm/TracKit)的用的pytorch版本一致，都是1.1，DCN编译依赖torch版本，可否考虑将项目torch版本升级到1.6以上？

**Comment by JudasDie** [comment]
> [老项目](https://github.com/researchmm/TracKit)的用的pytorch版本一致，都是1.1，DCN编译依赖torch版本，可否考虑将项目torch版本升级到1.6以上？

如果你用不到DCN的话可以考虑注释掉DCN的import，然后正常用pytorch1.7就可以，我现在是这样用的。

**Comment by codylcs** [comment]
> > [老项目](https://github.com/researchmm/TracKit)的用的pytorch版本一致，都是1.1，DCN编译依赖torch版本，可否考虑将项目torch版本升级到1.6以上？
> 
> 如果你用不到DCN的话可以考虑注释掉DCN的import，然后正常用pytorch1.7就可以，我现在是这样用的。

可以，亲测有效，感谢及时回复

**Comment by JudasDie** [comment]
> > > [老项目](https://github.com/researchmm/TracKit)的用的pytorch版本一致，都是1.1，DCN编译依赖torch版本，可否考虑将项目torch版本升级到1.6以上？
> > 
> > 
> > 如果你用不到DCN的话可以考虑注释掉DCN的import，然后正常用pytorch1.7就可以，我现在是这样用的。
> 
> 可以，亲测有效，感谢及时回复

木得事，加油。

**Comment by PLester** [comment]
@codylcs 你可以将原本项目中的DCN替换成这个版本，然后，checkout到你对应的版本，链接如下：
https://github.com/lbin/DCNv2/tree/pytorch_1.6 （支持Pytorch1.5-1.7）
