### ISSUE TITLE
Ocean给出的结果与论文之间的差异问题

### ISSUE THREAD

**Issue by Soarkey** [JudasDie/SOTS#50]
您好，感谢您提出的卓越工作！
这里有一些让我存在困惑的结果问题，希望向您请教一下！

我在 Ocean 论文中得到到的VOT2019结果为 
```
offline版本 A 0.590 | R 0.376 | EAO 0.327
online版本 A 0.594 | R 0.316 | EAO 0.350
```
但您提供的 Google Drive 中的结果只有 Ocean_VOT2019_0.323 文件夹，测试的指标为
```
A 0.598 | R  0.401 | EAO 0.323
```
请问 EAO 0.323 的是哪一个版本呢？为什么和论文会有这么大的差异呢？

谢谢！💖

**Comment by JudasDie** [comment]
> 您好，感谢您提出的卓越工作！ 这里有一些让我存在困惑的结果问题，希望向您请教一下！
> 
> 我在 Ocean 论文中得到到的VOT2019结果为
> 
> ```
> offline版本 A 0.590 | R 0.376 | EAO 0.327
> online版本 A 0.594 | R 0.316 | EAO 0.350
> ```
> 
> 但您提供的 Google Drive 中的结果只有 Ocean_VOT2019_0.323 文件夹，测试的指标为
> 
> ```
> A 0.598 | R  0.401 | EAO 0.323
> ```
> 
> 请问 EAO 0.323 的是哪一个版本呢？为什么和论文会有这么大的差异呢？
> 
> 谢谢！💖

你好，0.323和0.327看起来没什么区别，千分位了。这是个新库，结果都是重新训练的，不过和原文基本没差异。这个库ocean只给了offline版本，默认的对比对象时offline版本。

**Comment by Soarkey** [comment]
了解了，感谢解答！
