### ISSUE TITLE
[MOT/CSTrack]关于预训练权重

### ISSUE THREAD

**Issue by 1145284121** [JudasDie/SOTS#51]
感谢开源
tutorial中链接给出的yolov5l.pt   是仅包括yolo官方给出的backbone和检测head权重吗？
还是包含了CCN,SAAN这些部分，您自己进行预训练的呢？

**Comment by H11zang** [comment]
只包括了backbone和neck的权重，其他的权重都是随机初始化后训练的，没有再预训练。

**Comment by 1145284121** [comment]
1，感谢回复
