### ISSUE TITLE
pretrained weight

### ISSUE THREAD

**Issue by QiyuLuo** [JudasDie/SOTS#52]
Download the [link](https://drive.google.com/drive/folders/1UE6Y09W08TqKSKwGdsAwgjwixo9KSgVm) in the pre-training weights is compressed package, how should this be used?
**RuntimeError**: snapshot/Ocean.pth is a zip archive (did you mean to use torch.jit.load()?)

**Comment by JudasDie** [comment]
> Download the [link](https://drive.google.com/drive/folders/1UE6Y09W08TqKSKwGdsAwgjwixo9KSgVm) in the pre-training weights is compressed package, how should this be used? **RuntimeError**: snapshot/Ocean.pth is a zip archive (did you mean to use torch.jit.load()?)

Hi, sorry for the delayed replay. It seems that your pytorch version is not right.

**Comment by QiyuLuo** [comment]
> 

I am using pytorch1.8, this code does not support?

**Comment by JudasDie** [comment]
> > 
> 
> I am using pytorch1.8, this code does not support?

![image](https://user-images.githubusercontent.com/24988988/158940922-89a3df4e-d937-4c21-9faf-a4ab87dc6ed1.png)

I have tried to load the model with torch 1.8.0, as the figures.
