### ISSUE TITLE
OMC for FairMOT

### ISSUE THREAD

**Issue by Ahnsun** [JudasDie/SOTS#53]
Hi, I noticed that OMC was used for FairMOT in the paepr. Could you please provide the code about this? It would help me a lot! Thanks!

**Comment by H11zang** [comment]
Thanks for your interest. The code is on my school's computer, but I can't go back to school recently due to travel limitations caused by COVID-19. If you aren't in a hurry, I can provide it to you after I go back to school.

**Comment by JamesLiao714** [comment]
I need it too~ Thanks for sharing the code.

**Comment by Ahnsun** [comment]
Sure, you can send to my email yuen@hust.edu.cn, thanks a lot!

**Comment by JuntongMeng** [comment]
@H11zang  can you send me a copy, thanks

**Comment by JuntongMeng** [comment]
> Sure, you can send to my email [yuen@hust.edu.cn](mailto:yuen@hust.edu.cn), thanks a lot!
have you received the code, can you send it to my email to communicate, thank you   mengjuntong@stu.hebust.edu.cn

**Comment by liu0623** [comment]
@Ahnsun 可以发我一份吗，谢谢了

**Comment by sunyining99** [comment]
Thank you for your great work, I would like to learn how to use the recheck network, when you have time could you send me a copy? My email is sunyining99@126.com.Thank you again.

**Comment by shinaushin** [comment]
@Ahnsun  @JamesLiao714 @H11zang @JuntongMeng Can I also have a copy shinaushin@gmail.com?

thank you!

**Comment by JennyJJJJJJ** [comment]
@Ahnsun @JamesLiao714 @H11zang @JuntongMeng Can I also have a copy 1005118703@qq.com ?

Thanks a lot !

**Comment by 1145284121** [comment]
@Ahnsun @JamesLiao714 @H11zang @JuntongMeng Can I also have a copy [1145284121@qq.com]?

Thanks a lot !

**Comment by HangZheng66** [comment]
Can I also have a copy [zhenghang@zjut.edu.cn] thanks

**Comment by cgg99** [comment]
@shinaushin @H11zang @Ahnsun @1145284121 @JamesLiao714 Can I also have a copy [645179723@qq.com](url) Thanks a lot !
