### ISSUE TITLE
access to cstrack pretrained model

### ISSUE THREAD

**Issue by sieumap43** [JudasDie/SOTS#54]
Hi. Thank you for your great work. May I have the access to the cstrack pre-trained model? I cannot use my google drive account to download from your [link](https://drive.google.com/file/d/1x0HUDD9t6mnHi3q2N3Uf4gtmBBwPvAd7/view?usp=sharing). Please add my gmail barbaradebasin@gmail.com.

**Comment by H11zang** [comment]
I have shared it with you.

**Comment by sieumap43** [comment]
Ok thank you very much!
