### ISSUE TITLE
多类别跟踪

### ISSUE THREAD

**Issue by HX-uan** [JudasDie/SOTS#55]
你好，请问将MOT中的CSTrack修改为支持多类别的需要修改哪些参数?

**Comment by H11zang** [comment]
我没有尝试过哈，但是理论上如果embedding够区分多个类别的ID的话，只需要去修改detection的类别就可以了。

**Comment by HX-uan** [comment]
detection是指"CSTrack\experiments\model_set\CSTrack.yaml"里面的nc吗?

**Comment by HX-uan** [comment]
非常感谢您的回复
