### ISSUE TITLE
cstrack测试模型时得到的结果为NAN,或许是权重不对应？

### ISSUE THREAD

**Issue by Soyad-yao** [JudasDie/SOTS#60]
当我按照cstrack.md中的步骤进行模型的测试时，我的命令如下：
 python test_cstrack.py --nms_thres 0.6 --conf_thres 0.5 --weights ../weights/cstrack.pt --data_dir ../dataset --device 0 --test_mot17 True --vis_state 1
得到的结果为：
2022-05-06 10:40:17 [INFO]: start seq: MOT17-01-SDP
Creating model...

78,863,078 total parameters.
2022-05-06 10:40:19 [INFO]: Processing frame 0 (100000.00 fps)
2022-05-06 10:40:54 [INFO]: Processing frame 220 (8.14 fps)
2022-05-06 10:40:57 [INFO]: Processing frame 240 (8.16 fps)
2022-05-06 10:41:00 [INFO]: Processing frame 260 (8.18 fps)
2022-05-06 10:41:03 [INFO]: Processing frame 280 (8.20 fps)
2022-05-06 10:41:06 [INFO]: Processing frame 300 (8.21 fps)
2022-05-06 10:41:09 [INFO]: Processing frame 320 (8.21 fps)
2022-05-06 10:41:30 [INFO]: Time elapsed: 54.46 seconds, FPS: 8.26
             IDF1  IDP  IDR Rcll Prcn GT MT PT ML   FP FN IDs  FM  MOTA MOTP IDt IDa IDm
MOT17-01-SDP 0.0% 0.0% nan% nan% 0.0%  0  0  0  0 4293  0   0   0 -inf%  nan   0   0   0
OVERALL      0.0% 0.0% nan% nan% 0.0%  0  0  0  0 4293  0   0   0 -inf%  nan   0   0   0
detection_num: [4293] 4293
id_num: [53] 53
请问是什么原因造成这样的结果，数据需要进行预处理吗，非常感谢你突出的工作！

**Comment by JudasDie** [comment]
> 当我按照cstrack.md中的步骤进行模型的测试时，我的命令如下： python test_cstrack.py --nms_thres 0.6 --conf_thres 0.5 --weights ../weights/cstrack.pt --data_dir ../dataset --device 0 --test_mot17 True --vis_state 1 得到的结果为： 2022-05-06 10:40:17 [INFO]: start seq: MOT17-01-SDP Creating model...
> 
> 78,863,078 total parameters. 2022-05-06 10:40:19 [INFO]: Processing frame 0 (100000.00 fps) 2022-05-06 10:40:54 [INFO]: Processing frame 220 (8.14 fps) 2022-05-06 10:40:57 [INFO]: Processing frame 240 (8.16 fps) 2022-05-06 10:41:00 [INFO]: Processing frame 260 (8.18 fps) 2022-05-06 10:41:03 [INFO]: Processing frame 280 (8.20 fps) 2022-05-06 10:41:06 [INFO]: Processing frame 300 (8.21 fps) 2022-05-06 10:41:09 [INFO]: Processing frame 320 (8.21 fps) 2022-05-06 10:41:30 [INFO]: Time elapsed: 54.46 seconds, FPS: 8.26 IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm MOT17-01-SDP 0.0% 0.0% nan% nan% 0.0% 0 0 0 0 4293 0 0 0 -inf% nan 0 0 0 OVERALL 0.0% 0.0% nan% nan% 0.0% 0 0 0 0 4293 0 0 0 -inf% nan 0 0 0 detection_num: [4293] 4293 id_num: [53] 53 请问是什么原因造成这样的结果，数据需要进行预处理吗，非常感谢你突出的工作！

你好，是因为MOT的测试集没有label,所以评测显示NAN，可以忽略，提交MOT Challenge可以查看对应结果。

> 当我按照cstrack.md中的步骤进行模型的测试时，我的命令如下： python test_cstrack.py --nms_thres 0.6 --conf_thres 0.5 --weights ../weights/cstrack.pt --data_dir ../dataset --device 0 --test_mot17 True --vis_state 1 得到的结果为： 2022-05-06 10:40:17 [INFO]: start seq: MOT17-01-SDP Creating model...
> 
> 78,863,078 total parameters. 2022-05-06 10:40:19 [INFO]: Processing frame 0 (100000.00 fps) 2022-05-06 10:40:54 [INFO]: Processing frame 220 (8.14 fps) 2022-05-06 10:40:57 [INFO]: Processing frame 240 (8.16 fps) 2022-05-06 10:41:00 [INFO]: Processing frame 260 (8.18 fps) 2022-05-06 10:41:03 [INFO]: Processing frame 280 (8.20 fps) 2022-05-06 10:41:06 [INFO]: Processing frame 300 (8.21 fps) 2022-05-06 10:41:09 [INFO]: Processing frame 320 (8.21 fps) 2022-05-06 10:41:30 [INFO]: Time elapsed: 54.46 seconds, FPS: 8.26 IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP IDt IDa IDm MOT17-01-SDP 0.0% 0.0% nan% nan% 0.0% 0 0 0 0 4293 0 0 0 -inf% nan 0 0 0 OVERALL 0.0% 0.0% nan% nan% 0.0% 0 0 0 0 4293 0 0 0 -inf% nan 0 0 0 detection_num: [4293] 4293 id_num: [53] 53 请问是什么原因造成这样的结果，数据需要进行预处理吗，非常感谢你突出的工作！

你好，是因为MOT的测试集没有label,所以评测显示NAN，可以忽略，提交MOT Challenge可以查看对应结果。

**Comment by Soyad-yao** [comment]
好的，谢谢您的回答

**Comment by Bian-666** [comment]
> 好的，谢谢您的回答

请问您复现cstrack了吗，在mot17上的mota能达到74.9吗
