### ISSUE TITLE
CSTrack-S has poor training results

### ISSUE THREAD

**Issue by HeBotong** [JudasDie/SOTS#71]
Hi, thank you for your excellent work.
 When I trained CSTrack-S on MOT17, I got MOTA: 64.9 and IDF1: 66.7 scores, which is far from your paper's 72.9 and 70.3.
The parameters in the training process are all set according to the original settings in CSTrack.yaml. What might be the problem?

**Comment by Hoyoak** [comment]
Hello, sorry for the bothering, i got the same situation. Did you fix it?
