### ISSUE TITLE
博士，OceanPlus 论文中了没呢？

### ISSUE THREAD

**Issue by codylcs** [JudasDie/SOTS#8]

**Comment by JudasDie** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不幸没有。投期刊了。
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    


    --From: Zhang Zhipeng Institution: National Laboratory of Pattern Recognition Address: 95 Zhongguancun East Road, 100190, BEIJING, CHINA Email: zhangzhipeng2017@ia.ac.cn  Best Wishes

        
    
     

    在2021年3月2日 10:34，codylcs<notifications@github.com> 写道：

**Comment by codylcs** [comment]
录取率越来越低了，这么优秀的文章不中十分可惜啊，金子总会发光的

**Comment by JudasDie** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        谢谢。文章中不中都是玄学，主要对得起自己就好。
        
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    


    --From: Zhang Zhipeng Institution: National Laboratory of Pattern Recognition Address: 95 Zhongguancun East Road, 100190, BEIJING, CHINA Email: zhangzhipeng2017@ia.ac.cn  Best Wishes

        
    
     

    在2021年3月2日 10:57，codylcs<notifications@github.com> 写道： 




录取率越来越低了，这么优秀的文章不中十分可惜啊，金子总会发光的

**Comment by codylcs** [comment]
也可能是社会学，心态好就行
