### ISSUE TITLE
How to train my own data

### ISSUE THREAD

**Issue by wangmhua** [JudasDie/SOTS#9]
当我运行train_cstrack.py进行训练自己的数据集后，生成best_mot_test.pt权重。再将此权重进行测试，发现测试的结果图像上没有显示关联的id，请问这是什么原因？该如何解决呢？万分感谢！

**Comment by H11zang** [comment]
没有显示的关联id指的是有检测结果，没有获得id吗？可以查看下生成的txt文件是否有id的
