### ISSUE TITLE
Inquiry about the Dataset for the Paper "Divert More Attention to Vision-Language Object Tracking"

### ISSUE THREAD

**Issue by Xuchen-Li** [JudasDie/SOTS#99]
### Description of Inquiry
I am interested in the dataset associated with your paper "Divert More Attention to Vision-Language Object Tracking," where you present a method for vision-language object tracking. I am eager to access this dataset for further research and experimentation.

### Expected Open-Source Timing
Is there an estimated timeline for when the dataset will be made publicly available? If so, could you provide a target date or a general time frame?

Thank you for your attention and support. I look forward to your response!

**Comment by Kingzerd** [comment]
Hi! Very thanks for your interest in our work!

The attribute language annotations have been released with the sentence language annotations of VLT_SCAR and VLT_TT, you can find them [here](https://drive.google.com/drive/folders/1yuY-794ofnCaFtfukT_h-UY047-Zmpdy) (or subfolder `attribute words` in the [common folder](https://drive.google.com/drive/folders/1WMYe4gXWp8wMKDdDit6eqq32-8tg8uAV)).

The attribute annotation of each dataset  is saved in the `dict` form (`video names: attribute words`) like,

> {
>     'airplane-1': 'plane,vehicle,white,right',
>     'airplane-2': 'plane,vehicle,gray,center',
>     ...
> }

Loading the pth files with `torch.load` is just enough!

**Comment by Xuchen-Li** [comment]
Thanks a lot!
